config/routes.rb
Rails.application.routes.draw do

  resources :histories

  resources :softwares

  resources :servers

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'users/new'

  get 'static_pages/home'
  get 'static_pages/help'
  get "static_pages/about"
  get "static_pages/contact"

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/software',to: 'softwares#new',        via: 'get'
  match '/histories/:id/install', to: 'histories#install',  via: 'get'

end

app/models/history.rb
class History < ActiveRecord::Base
  belongs_to :server
  belongs_to :software
  default_scope -> { order('created_at DESC') }
  validates :server_id, presence: true
  validates :software_id, presence: true
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :set_history, only: [:show, :edit, :update, :destroy]

  # GET /histories
  # GET /histories.json
  def index
    @histories = History.all
  end

  # GET /histories/1
  # GET /histories/1.json
  def show
  end

  def install
    # @histories = History.all
    @all_info[:server] = Server.all
    @all_info[:software] = Software.all
  end
  # GET /histories/new
  def new
    @history = History.new
  end

  # GET /histories/1/edit
  def edit
  end

  # POST /histories
  # POST /histories.json
  def create
    @history = History.new(history_params)

    respond_to do |format|
      if @history.save
        format.html { redirect_to @history, notice: 'History was successfully created.' }
        format.json { render :show, status: :created, location: @history }
      else
        format.html { render :new }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /histories/1
  # PATCH/PUT /histories/1.json
  def update
    respond_to do |format|
      if @history.update(history_params)
        format.html { redirect_to @history, notice: 'History was successfully updated.' }
        format.json { render :show, status: :ok, location: @history }
      else
        format.html { render :edit }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1
  # DELETE /histories/1.json
  def destroy
    @history.destroy
    respond_to do |format|
      format.html { redirect_to histories_url, notice: 'History was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_history
      @history = History.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def history_params
      params.require(:history).permit(:server_id, :software_id)
    end
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/views/histories/_form.html.erb
<%= form_for(@history) do |f| %>
  <% if @history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@history.errors.count, "error") %> prohibited this history from being saved:</h2>

      <ul>
      <% @history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :server_id %><br>
    <%= f.number_field :server_id %>
  </div>
  <div class="field">
    <%= f.label :software_id %><br>
    <%= f.number_field :software_id %>
  </div>
  <div class="action">
    <%= f.submit %>
  </div>
<% end %>

app/views/histories/_forminstall.html.erb
<%= form_for(@all_info) do |f| %>
<% if @server.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@server.errors.count, "error") %> prohibited this server from being saved:</h2>

  <ul>
    <% @server.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="row">
  <div class="span6 offset3">
    <div class="field">
      <%= f.label :server %><br>

      <% Server.all.each do |server| %>
      <label class="checkbox-inline">
        <input type="checkbox"><%= server.name %><%= ' (ip: ' %><%= server.ip %><%= ')' %>
      </label>
      <% end %>

    </div>
  </div>
  <div class="span6 offset3">
    <div class="field">
      <%= f.label :software %><br>

      <% Software.all.each do |software| %>
      <label class="checkbox-inline">
        <input type="checkbox"><%= software.name %><%= ' (version: ' %><%= software.version %><%= ')' %>
      </label>
      <% end %>


    </div>
  </div>
</div>
<% end %>

app/views/histories/edit.html.erb
<h1>Editing history</h1>

<%= render 'form' %>

<%= link_to 'Back', histories_path %>

app/views/histories/index.html.erb
<h1 class="text-success">List of histories</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Server</th>
      <th>Software</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @histories.each do |history| %>
      <tr>
        <td><%= history.server_id %></td>
        <td><%= history.software_id %></td>
        <td><%= link_to 'Edit', edit_history_path(history) %></td>
        <td><%= link_to 'Destroy', history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New History', new_history_path %>

app/views/histories/install.html.erb
<h1 style= "color: green">Install Info</h1>

<%= render 'forminstall' %>

app/views/histories/new.html.erb
<h1>New history</h1>

<%= render 'form' %>

<%= link_to 'Back', histories_path %>

app/views/histories/show.html.erb
<p>
  <strong>Server:</strong>
  <%= @history.server_id %>
</p>

<p>
  <strong>Software:</strong>
  <%= @history.software_id %>
</p>

<%= link_to 'Edit', edit_history_path(@history) %> |
<%= link_to 'Back', histories_path %>