config/routes.rb
Rails.application.routes.draw do

  resources :histories

  resources :softwares

  resources :servers

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'users/new'

  get 'static_pages/home'
  get 'static_pages/help'
  get "static_pages/about"
  get "static_pages/contact"

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/software',to: 'softwares#new',        via: 'get'
  match '/histories/:id/install', to: 'histories#install',  via: 'get'

end

app/models/software.rb
class Software < ActiveRecord::Base
  default_scope -> { order('created_at DESC') }
  validates :name, presence: true
  validates :version, presence: true
end

app/controllers/softwares_controller.rb
class SoftwaresController < ApplicationController
  before_action :set_software, only: [:show, :edit, :update, :destroy]

  # GET /softwares
  # GET /softwares.json
  def index
    @softwares = Software.all
  end

  # GET /softwares/1
  # GET /softwares/1.json
  def show
    @software = Software.find(params[:id])
  end

  # GET /softwares/new
  def new
    @software = Software.new
  end

  # GET /softwares/1/edit
  def edit
  end

  # POST /softwares
  # POST /softwares.json
  def create
    @software = Software.new(software_params)

    respond_to do |format|
      if @software.save
        format.html { redirect_to @software, notice: 'Software was successfully created.' }
        format.json { render :show, status: :created, location: @software }
      else
        format.html { render :new }
        format.json { render json: @software.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /softwares/1
  # PATCH/PUT /softwares/1.json
  def update
    respond_to do |format|
      if @software.update(software_params)
        format.html { redirect_to @software, notice: 'Software was successfully updated.' }
        format.json { render :show, status: :ok, location: @software }
      else
        format.html { render :edit }
        format.json { render json: @software.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /softwares/1
  # DELETE /softwares/1.json
  def destroy
    @software.destroy
    respond_to do |format|
      format.html { redirect_to softwares_url, notice: 'Software was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_software
      @software = Software.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def software_params
      params.require(:software).permit(:name, :version)
    end
end

app/helpers/softwares_helper.rb
module SoftwaresHelper
end

app/views/softwares/_form.html.erb
<%= form_for(@software) do |f| %>
  <% if @software.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@software.errors.count, "error") %> prohibited this software from being saved:</h2>

      <ul>
      <% @software.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :version %><br>
    <%= f.text_field :version %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/softwares/edit.html.erb
<h1>Editing software</h1>

<%= render 'form' %>

<%= link_to 'Back', softwares_path %>

app/views/softwares/index.html.erb
<h1 class="text-success">List of softwares</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Version</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @softwares.each do |software| %>
      <tr>
        <td><%= software.name %></td>
        <td><%= software.version %></td>
        <td><%= link_to 'Edit', edit_software_path(software) %></td>
        <td><%= link_to 'Destroy', software, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Software', new_software_path %>

app/views/softwares/new.html.erb
<h1>New software</h1>

<%= render 'form' %>

<%= link_to 'Back', softwares_path %>

app/views/softwares/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @software.name %>
</p>

<p>
  <strong>Version:</strong>
  <%= @software.version %>
</p>

<%= link_to 'Edit', edit_software_path(@software) %> |
<%= link_to 'Back', softwares_path %>