config/routes.rb
Rails.application.routes.draw do

  resources :histories

  resources :softwares

  resources :servers

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'users/new'

  get 'static_pages/home'
  get 'static_pages/help'
  get "static_pages/about"
  get "static_pages/contact"

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/software',to: 'softwares#new',        via: 'get'
  match '/histories/:id/install', to: 'histories#install',  via: 'get'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ansible_Tower</title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "Ansible Tower", root_path, id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "Help", '#' %></li>
              <% if signed_in? %>
                <li id="fat-menu" class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Account <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Profile", current_user %></li>
                    <li class="divider"></li>
                    <li>
                      <%= link_to "Sign out", signout_path, method: "delete" %>
                    </li>
                  </ul>
                </li>
              <% else %>
                <li><%= link_to "Sign in", signin_path %></li>
              <% end %>
            </ul>
          </nav>
    </header>
    <br>
    <br>
    <div>
    <ul class="nav nav-pills">
    <% if signed_in? %>
      <li class="active">
        <a href="http://localhost:3000">HOME</a>
      </li>
      <li><%= link_to "SERVER INFO", servers_path %></li>
      <li><%= link_to "SOFTWARE INFO", softwares_path %></li>
      <li><a href="/histories/:id/install">YOUR INSTALL</a></li>
      <li><%= link_to "HISTORY YOUR INSTALL", histories_path %></li>
      <% end %>
    </ul>
    </div>
     <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>

    <footer class="footer">
      <small> Ansible Tower by Solar_Team</small>
      <nav>
        <ul>
          <li><%= link_to "About", '#' %></li>
          <li><%= link_to "Contact", '#'%></li>
        </ul>
      </nav>
    </footer>

  </body>
</html>